:lipstick: added option to keep style on drilled paths
equinor/amplify-component-lib pull request #694
Opened 2024-08-14 09:24 UTC by Brynjulf

2024-09-03 10:41 UTC, arkadiy93 requested changes
you need to bump the version of the package

2024-09-03 12:31 UTC, arkadiy93 commented on src/organisms/SideBar/MenuItem.tsx
> +   */
Seems like it does 😸 

![image](https://github.com/user-attachments/assets/d16b7e30-87e1-4f74-b962-26e99c1d4b2f)

2024-09-03 12:31 UTC, Brynjulf commented on src/organisms/SideBar/MenuItem.tsx
> +   */
This is the js doc format, when you look at the property while using the component this comment should accurately show when you are looking at what the property should do

2024-09-03 12:31 UTC, Brynjulf commented on src/organisms/SideBar/MenuItem.tsx
> +   */
![Screenshot 2024-09-03 at 14 31 01](https://github.com/user-attachments/assets/23beb839-156f-4b6a-b356-8afe7afcadbe)

2024-09-03 13:04 UTC, aslakihle commented on src/organisms/SideBar/MenuItem.tsx
> +   */
ok, nice! 
Was thinking of this, but guess its a way to do the same thing:
![image](https://github.com/user-attachments/assets/d2e2e9b0-318c-4023-bb31-e239c9deafad)

2024-09-03 13:04 UTC, aslakihle approved these changes

2024-09-04 07:24 UTC, arkadiy93 approved these changes

2024-09-04 07:24 UTC, merged