:bug: stop impersonating if switching apps
equinor/amplify-component-lib pull request #860
Opened 2024-11-11 10:57 UTC by bjorngoa

2024-11-11 12:24 UTC, mariush2 requested changes

2024-11-11 12:26 UTC, bjorngoa commented on src/organisms/TopBar/Account/Account.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
![image](https://github.com/user-attachments/assets/13f411ef-5e7d-4922-a72e-be7ff8c9afda)

2024-11-11 12:41 UTC, mariush2 requested changes

2024-11-11 12:41 UTC, mariush2 commented on src/organisms/TopBar/Account/Account.tsx
> +  }, [activeImpersonationUser, APPLICATION_NAME]);
```suggestion
  useEffect(() => {
    if (
      activeImpersonationUser &&
      activeImpersonationUser.appName != undefined &&
      activeImpersonationUser.appName != APPLICATION_NAME
    ) {
      endImpersonation();
    }
  }, [activeImpersonationUser, APPLICATION_NAME, endImpersonation]);
```

2024-11-11 12:41 UTC, mariush2 commented on src/organisms/TopBar/Account/Account.tsx
> +  const { mutateAsync: endImpersonation } = useStopImpersonation();
```suggestion
  const { mutate: endImpersonation } = useStopImpersonation();
```

2024-11-11 12:42 UTC, mariush2 commented on src/organisms/TopBar/Account/Account.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Added a suggestion that should work

2024-11-12 07:21 UTC, mariush2 approved these changes

2024-11-12 07:57 UTC, merged